# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4c522f57784c6d8aa270fa10a753dc126fac917bddb330c39e0cb6d6aaed91403a507fc20489b10214b38a6e23bd496cf762e350aac863a307ede738634da5e

test:
  secret_key_base: 0b88683956facee04b206ff5d6f6d891128453139b5522f7114674a80614b66427a2d137633f95827ba1734532c3c13b97071e76776ecd0c6e133e68b9348c5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
